// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwAuSUTuGUzhDbf9QLRZS43dXHTp0fGZ8',
    appId: '1:322288772938:web:0d6e03db9d5aa61a9f83b3',
    messagingSenderId: '322288772938',
    projectId: 'tickettrek-e850e',
    authDomain: 'tickettrek-e850e.firebaseapp.com',
    storageBucket: 'tickettrek-e850e.firebasestorage.app',
    measurementId: 'G-F002241ELV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWsRMf-1Bvmkc_ey9y-hiZh_1eqdrSEoE',
    appId: '1:322288772938:android:9f720759ca4863c29f83b3',
    messagingSenderId: '322288772938',
    projectId: 'tickettrek-e850e',
    storageBucket: 'tickettrek-e850e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLM1Tu7k27a0VaDvIy8wLX6L8Aoo_S3c',
    appId: '1:322288772938:ios:b85ef7361712be009f83b3',
    messagingSenderId: '322288772938',
    projectId: 'tickettrek-e850e',
    storageBucket: 'tickettrek-e850e.firebasestorage.app',
    iosBundleId: 'com.example.ticketTrek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtLM1Tu7k27a0VaDvIy8wLX6L8Aoo_S3c',
    appId: '1:322288772938:ios:b85ef7361712be009f83b3',
    messagingSenderId: '322288772938',
    projectId: 'tickettrek-e850e',
    storageBucket: 'tickettrek-e850e.firebasestorage.app',
    iosBundleId: 'com.example.ticketTrek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwAuSUTuGUzhDbf9QLRZS43dXHTp0fGZ8',
    appId: '1:322288772938:web:e8176b76a7371ecb9f83b3',
    messagingSenderId: '322288772938',
    projectId: 'tickettrek-e850e',
    authDomain: 'tickettrek-e850e.firebaseapp.com',
    storageBucket: 'tickettrek-e850e.firebasestorage.app',
    measurementId: 'G-9QGL12TJK2',
  );
}
